package rules

import models.PlayerFoulEvent
import models.Player

declare UnsportsmanlikeConduct
    playerId: String
end

rule "CEP 1 - Check aggressive behavior"
    agenda-group "CEP"
    salience 100
    no-loop true
    when
        $p: Player($id: playerId, aggressive == false)
        Number(intValue >= 5) from accumulate(
            $e: PlayerFoulEvent(playerId == $id) over window:time(10m),
            count($e)
        )
    then
        modify($p){
            setAggressive(true)
        };
 end

 rule "CEP 2 - Check for increased disciplinary risk"
    agenda-group "CEP"
    salience 100
    no-loop true
    when
        $p: Player($id: playerId, increasedDisciplinaryRisk == false)
        Number(intValue >= 3) from accumulate(
            $e: PlayerFoulEvent(playerId == $id) over window:time(10m),
            count($e)
        )
    then
        modify($p){
            setIncreasedDisciplinaryRisk(true)
        };
end

rule "CEP 3 - Check for increasing disciplinary assessment intensity"
    agenda-group "CEP"
    salience 100
    no-loop true
    when
        $p: Player($id: playerId)
        $f1: PlayerFoulEvent(playerId == $id)
        $f2: PlayerFoulEvent(playerId == $id, this != $f1, this after[0s, 3m] $f1)

        not (PlayerFoulEvent(
                    this after $f1,
                    this before $f2
        ))
    then
        modify($p){
            setDisciplinaryAssessmentIntensity($p.getDisciplinaryAssessmentIntensity() + 1)
        };
end

rule "CEP 4a - Check for unsportsmanlike conduct"
    agenda-group "CEP"
    salience 100
    when
        $p: PlayerFoulEvent($id: playerId)
        Number(intValue >= 5) from accumulate(
            $e: PlayerFoulEvent(playerId == $id, contact == true) over window:time(10m),
            count($e)
        )
        not(UnsportsmanlikeConduct(playerId == $id))
    then
        insert(new UnsportsmanlikeConduct($id));
end

rule "CEP 4b - Remove unsportsmanlike conduct when player cooled down"
    agenda-group "CEP"
    salience 100
    when
        $uc: UnsportsmanlikeConduct($id: playerId)
        Number (intValue < 5) from accumulate(
            $e: PlayerFoulEvent(playerId == $id, contact == true) over window:time(10m),
            count($e)
        )
    then
        delete($uc);
end