package rules

import models.Player
import models.Incident
import enums.FoulType
import enums.Intensity
import enums.TackleControl
import enums.ContactPoint
import rules.UnsportsmanlikeConduct

//G1-1
rule "Set tackle intensity to HIGH for the last incident"
    agenda-group "MAIN"
    salience 95
    no-loop true
    when
        $p: Player($id: playerJerseyNumber, aggressive == true)
        $lastIncident: Incident(playerJerseyNumber == $id, foulType == FoulType.NON_EXISTENT, intensity != Intensity.HIGH)

        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 1");
        modify($lastIncident){
            setIntensity(Intensity.HIGH)
        };
end

//G1-2a
rule "Set tackle intensity when increased disciplinary risk - LOW"
    agenda-group "MAIN"
    salience 90
    no-loop true
    when
        $p: Player($id: playerJerseyNumber, increasedDisciplinaryRisk == true)
        $lastIncident: Incident(playerJerseyNumber == $id, foulType == FoulType.NON_EXISTENT, intensity == Intensity.LOW)
        not (Incident(
                    playerJerseyNumber == $id,
                    this after $lastIncident
        ))
    then
        System.out.println("Pravilo 2");
        modify($lastIncident){
            setIntensity(Intensity.MEDIUM)
        }
end

//G2-b
rule "Set tackle intensity when increased disciplinary risk - MEDIUM"
    agenda-group "MAIN"
    salience 80
    no-loop true
    when
        $p: Player($id: playerJerseyNumber, increasedDisciplinaryRisk == true)
        $lastIncident: Incident(playerJerseyNumber == $id, foulType == FoulType.NON_EXISTENT, intensity == Intensity.MEDIUM)
        not (Incident(
                    playerJerseyNumber == $id,
                    this after $lastIncident
        ))
    then
        System.out.println("Pravilo 3");
        modify($lastIncident){
            setIntensity(Intensity.HIGH)
        }
end

//G1-3a
rule "Increase tackle intensity - reason: assessment - LOW"
    agenda-group "MAIN"
    salience 80
    no-loop true
    when
       $p: Player($id: playerJerseyNumber, disciplinaryAssessmentIntensity >= 2)
       $lastIncident: Incident(playerJerseyNumber == $id, foulType == FoulType.NON_EXISTENT, intensity == Intensity.LOW)
       not (Incident(
           playerJerseyNumber == $id,
           this after $lastIncident
       ))
   then
        System.out.println("Pravilo 4");
       modify($lastIncident){
           setIntensity(Intensity.MEDIUM)
       }
end

//G1-3a
rule "Increase tackle intensity - reason: assessment - MEDIUM"
    agenda-group "MAIN"
   salience 90
   no-loop true
   when
       $p: Player($id: playerJerseyNumber, disciplinaryAssessmentIntensity >= 2)
       $lastIncident: Incident(playerJerseyNumber == $id, foulType == FoulType.NON_EXISTENT, intensity == Intensity.MEDIUM)
       not (Incident(
           playerJerseyNumber == $id,
           this after $lastIncident
       ))
   then
       System.out.println("Pravilo 5");
       modify($lastIncident){
           setIntensity(Intensity.HIGH)
       }
end

//G1-4
rule "Foul type - Unsportsmanlike Conduct"
    agenda-group "MAIN"
    salience 80
    no-loop true
    when
        $uc: UnsportsmanlikeConduct($id: playerJerseyNumber)
        $lastIncident: Incident(playerJerseyNumber == $id)
       not (Incident(
           playerJerseyNumber == $id,
           this after $lastIncident,
           foulType == FoulType.NON_EXISTENT
       ))
    then
        System.out.println("NESPORTSKO PONASANJE!");
        modify($lastIncident){
            setFoulType(FoulType.RECKLESS)
        };
end

//G1-5
rule "Foul type - Non-existent foul"
    agenda-group "MAIN"
    salience 70
    no-loop true
    when
        $p: Player($id: playerJerseyNumber)
        
        $lastIncident: Incident(
            playerJerseyNumber == $id,
            contact == false, 
            dangerousPlay == false,
            foulType == FoulType.NON_EXISTENT
        )
        
        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 6");
        modify($lastIncident){
            setFoulType(FoulType.NON_EXISTENT)
        };
end

//G1-6
rule "Foul type - dangerous play"
    agenda-group "MAIN"
    salience 70
    no-loop true
    when
        $p: Player($id: playerJerseyNumber)
        
        $lastIncident: Incident(
            playerJerseyNumber == $id,
            contact == false, 
            dangerousPlay == true,
            foulType == FoulType.NON_EXISTENT
        )
        
        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 7");
        modify($lastIncident){
            setFoulType(FoulType.CARELESS)
        };
end

//G1-7
rule "Check for careless foul"
    agenda-group "MAIN"
    salience 70
    no-loop true
    when
        $p: Player($id: playerJerseyNumber)
        
        $lastIncident: Incident(
            playerJerseyNumber == $id,
            contact == true, 
            intensity == Intensity.LOW,
            tackleControl == TackleControl.CONTROLLED,
            foulType == FoulType.NON_EXISTENT
        )
        
        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 8");
        modify($lastIncident){
            setFoulType(FoulType.CARELESS)
        }
end

//G1-8
rule "Check for reckless foul"
    agenda-group "MAIN"
    salience 70
    no-loop true
    when
        $p: Player($id: playerJerseyNumber)

        $lastIncident: Incident(
            playerJerseyNumber == $id,
            contact == true,
            (intensity == Intensity.MEDIUM || contactFromBehind == true),
            foulType == FoulType.NON_EXISTENT
        )

        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 9");
        modify($lastIncident){
            setFoulType(FoulType.RECKLESS)
        };
end

//G1-9
rule "Check for excesive foul"
    agenda-group "MAIN"
    salience 75
    no-loop true
    when
        $p: Player($id: playerJerseyNumber)

        $lastIncident: Incident(
            playerJerseyNumber == $id,
            contact == true,
            (intensity == Intensity.HIGH || (openFoot == true && contactPoint == ContactPoint.ABOVE_JOINT)),
            foulType == FoulType.NON_EXISTENT
        )

        not (Incident(
            playerJerseyNumber == $id,
            this after $lastIncident
        ))
    then
        System.out.println("Pravilo 10");
        modify($lastIncident){
            setFoulType(FoulType.EXCESSIVE)
        };
end
